### ISSUE TITLE
Add imap servers

### ISSUE THREAD

**Issue by joejulian** [GhostFlying/PortalWaitingList#12]
Please add the ability to connect to an imap server instead of gmail.

**Comment by GhostFlying** [comment]
I do not know what's situation where this is needed.

The app now is using Gmail API to improve the security so that the support
of IMAP will be considered but may not be added in a short time.

**Comment by joejulian** [comment]
I'm just trying to find one of these tools that uses imap since I don't use gmail. ipst claims to but it validates the username against an email address pattern. Since my imap server just uses a username without domain, it doesn't work.
